name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GH_TOKEN }}
          config_timezone: Europe/Paris

          plugin_lines: yes

          plugin_traffic: yes

          plugin_habits: yes
          plugin_habits_charts: yes

          plugin_followup: yes
          
          plugin_languages: yes
