name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Bratislava
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_languages: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_calendar: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 0
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          
